baseURL = 'https://evan-hossain.github.io'
languageCode = 'en-us'
title = 'Evan Hossain'
author = 'Evan Hossain'
theme = 'anatole'
summaryLength = 20
disqusShortname = "evan-portfolio"
# postSectionName = "Kotlin"

[params]
title = "Evan Hossain"
description = """
Software Engineer, Google
Dublin, Ireland
"""
profilePicture = "images/profile.jpeg"
contentratio = 0.7
gtagId = "G-K0HCZDVQ3Q"
readMore = true
relatedPosts = true
numberOfRelatedPosts = 3
googleSiteVerify = "-HcHMyg1C_v5T_MAHavmuOuJap7niqMo42q7sdJX_c4"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/evan-hossain/"
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/evan-hossain/"
[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:cse.evan@gmail.com"

## Math settings
[params.math]
enable = true # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "post"
  url = "/post/"

  [[menu.main]]
  name = "Kotlin"
  weight = 300
  identifier = "kotlin"
  url = "/kotlin/"

  [[menu.main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80

[sitemap]
  changefreq = 'always'
  filename = 'sitemap.xml'
  priority = 0.5
